[package]
name = "first-interp"
version = "0.1.0"
authors = ["Russell Mirabelli <russell@mirabellifamily.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
